### ISSUE TITLE
A Pokemon API

### ISSUE THREAD

**Issue by ghost** [yurecouto/PyPokemon#1]
you should take assistance from this RESTful api called pokeapi(very creative). You can find it here: https://pokeapi.co/
the requests python package should help you retrieve data from it.
example:
`
import requests
def get_pokemon(pokemon):
    """get the json data of the pokemon
    you can use this as input for the functions. Example
    charizard_json = get_pokemon('charizard')
    print(get_pokemon_name(charizard_json))
    """
    if type(pokemon) != str:
        pokemon = pokemon(str)
    json_output = requests.get(f"https://pokeapi.co/api/v2/pokemon/{pokemon}")
    filtered_output = json_output.json()
    return filtered_output
`

^ this returns the json information all about a pokemon. documention here:https://pokeapi.co/docs/v2#pokemon-section

There are multiple resources you can get from this api like berries and moves.

**Comment by ghost** [comment]
for some reason github sent it without multiple lines but here is an image

![image](https://user-images.githubusercontent.com/57762641/124545343-824b9300-de46-11eb-97dc-383e42bfb050.png)

**Comment by yurecouto** [comment]
Hi, thank you for writing and for the tip! 

I don't know if I would use this for now, but probably I'll implement this in the future.
